# http proxy
http_proxy: http://user:pass@host:port

# docker variables
docker:
  http_proxy: "{{ http_proxy }}"
  no_proxy: localhost,127.0.0.1,repo.domian.com
  log_max_file: "5"
  log_max_size: 100m
  registry_mirror: https://repo.domain.com